config/routes.rb
ProjetoFinal::Application.routes.draw do

  resources :exames, except: [:edit, :update, :destroy] do
    member do
		  get :concluir
		  put :salvar_conclusao
	  end
	  
	  collection do
      get :concluidas
      get :consultar_concluidas
      get :consultar_marcadas
    end
	  
  end
  
  resources :marcacoes, except: [:edit, :update, :destroy] do
		member do
		  get :concluir
		  put :salvar_conclusao
	  end

	  collection do
      get :concluidas
      get :consultar_concluidas
      get :consultar_marcadas
    end
	end

  resources :especialidades

  devise_for :funcionarios, controllers: { registrations: 'funcionarios' }

  resources :funcionarios do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :pacientes do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :postos do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :medicos do
    collection do
      get :informacoes
      get :consultar
    end
  end

root to: "home#index"
 
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base

                              validates :nome, :cpf, :rg, :cartao_sus, :sexo, :data_nascimento, :estado_civil,
          :cor, :naturalidade, :grau_instrucao, :email, :telefone, :endereco,
          :bairro, :cidade, :estado, :cep, presence: true

  validates :email, format:/^.+\@.+\..+$/

  usar_como_cpf :cpf
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
    load_and_authorize_resource 
    before_filter :authenticate_funcionario!
  
  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pacientes }
    end
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
    @paciente = Paciente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paciente }
    end
  end

  # GET /pacientes/new
  # GET /pacientes/new.json
  def new
    @paciente = Paciente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paciente }
    end
  end

  # GET /pacientes/1/edit
  def edit
    @paciente = Paciente.find(params[:id])
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(params[:paciente])

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente cadastrado com sucesso.' }
        format.json { render json: @paciente, status: :created, location: @paciente }
      else
        format.html { render action: "new" }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pacientes/1
  # PUT /pacientes/1.json
  def update
    @paciente = Paciente.find(params[:id])

    respond_to do |format|
      if @paciente.update_attributes(params[:paciente])
        format.html { redirect_to @paciente, notice: 'Paciente alterado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente = Paciente.find(params[:id])
    @paciente.destroy

    respond_to do |format|
      format.html { redirect_to pacientes_url }
      format.json { head :no_content }
    end
  end

  def informacoes
  end

  def consultar
    nome = params[:nome]
    @pacientes = Paciente.where('UPPER(nome) LIKE ?', "%#{nome.upcase}%")
    render 'index'
  end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<div id="formulario">

  <%= semantic_form_for(@paciente) do |f| %>

      <fieldset class="dados_fieldset">
        <legend> Dados Pessoais</legend>
          <br>
          <%= f.input :nome %>
          <%= f.input :cpf, label: "CPF", input_html: opcoes_para_cpf %>
          <%= f.input :rg, label: "RG" %>
          <%= f.input :cartao_sus, label: "Cartão SUS" %>
          <%= f.input :data_nascimento, as: :string, label: "Data Nascimento",
          input_html: opcoes_para_data %>
          <%= f.input :sexo, as: :select, collection: ["Masculino", "Feminino"]%>
          <%= f.input :estado_civil, as: :select, collection: ["Solteiro", "Casado", "Separado", "Viúvo"] %>
          <%= f.input :cor, as: :select, collection: ["Negro", "Mulato Escuro", "Mulato Médio", "Mulato Claro", "Branco"] %>
          <%= f.input :naturalidade %>
          <%= f.input :grau_instrucao, label: "Grau Instrução"%>
      </fieldset>

      <br><br>

      <fieldset class="dados_fieldset">
        <legend> Dados Contato</legend>
           <br>
           <%= f.input :email, label: "E-mail"%>
           <%= f.input :telefone, input_html: opcoes_para_telefone %>
           <%= f.input :endereco, label: "Endereço"%>
           <%= f.input :complemento %>
           <%= f.input :bairro %>
           <%= f.input :cidade %>
           <%= f.input :estado, as: :select, collection: ["Acre", "Alagoas", "Amazonas", "Amapá", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rondônia", "Rio Grande do Sul", "Roraima", "Santa Catarina", "Sergipe", "São Paulo", "Tocantins"] %>
           <%= f.input :cep, label: "CEP", input_html: opcoes_para_cep %>
           <%= f.input :profissao, label: "Profissão" %>
           <%= f.input :observacao, label: "Observação", input_html: opcoes_para_observacao %>

      </fieldset>


      <br><br>

      <%= f.submit 'Salvar' %>
<% end %>

</div>

app/views/pacientes/edit.html.erb
<h1>Alterar Paciente</h1>

<%= render 'form' %>

app/views/pacientes/index.html.erb
<div id="paciente">

<h1>Consultar Paciente</h1>

<div id='consulta'>
   <%= form_tag consultar_pacientes_path, method: :get do %>
     <%= label_tag :nome, 'Busca por nome' %>
     <%= text_field_tag :nome %>
     <%= submit_tag 'Buscar' %>
   <% end %>
</div>

<table id="relatorio">
  <tr>
  <tr>
    <th>Nome</th>
    <th>Cartao sus</th>
    <th>Email</th>
    <th>Telefone</th>
    <th>Profissao</th>
    <th>Observacao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pacientes.each do |paciente| %>
  <tr>
    <td><%= paciente.nome %></td>
    <td><%= paciente.cartao_sus %></td>
    <td><%= paciente.email %></td>
    <td><%= paciente.telefone %></td>
    <td><%= paciente.profissao %></td>
    <td><%= paciente.observacao %></td>
    <td><%= link_to 'Ver', paciente %></td>
    <td><%= link_to 'Alterar', edit_paciente_path(paciente) %></td>
    <td><%= link_to 'Apagar', paciente, confirm: 'Realmente deseja apagar?', method: :delete %></td>
   </tr>
<% end %>
</table>

<br />

</div>

app/views/pacientes/informacoes.html.erb
<div id="paciente">
  <h1>Paciente</h1>

  <div id="informacoes">
    <p>Paciente é aquela pessoa que consulta o médico ou o profissional da área de saúde.</p>

    <p>Pacientes especiais são todos aqueles indivíduos que se desviam física, intelectual, social e emocionalmente daquilo que se considera padrão de normalidade.<p>
  </div>



</div>

app/views/pacientes/new.html.erb
<div id="paciente">

<h1>Cadastrar Paciente</h1>

<%= render 'form' %>

</div>

app/views/pacientes/show.html.erb
<div id="paciente">

<p>
  <b>Nome:</b>
  <%= @paciente.nome %>
</p>

<p>
  <b>CPF:</b>
  <%= @paciente.cpf %>
</p>

<p>
  <b>RG:</b>
  <%= @paciente.rg %>
</p>

<p>
  <b>Cartão SUS:</b>
  <%= @paciente.cartao_sus %>
</p>

<p>
  <b>Data Nascimento:</b>
  <%= @paciente.data_nascimento %>
</p>

<p>
  <b>Sexo:</b>
  <%= @paciente.sexo %>
</p>

<p>
  <b>Estado civil:</b>
  <%= @paciente.estado_civil %>
</p>

<p>
  <b>Cor:</b>
  <%= @paciente.cor %>
</p>

<p>
  <b>Naturalidade:</b>
  <%= @paciente.naturalidade %>
</p>

<p>
  <b>Grau Instrução:</b>
  <%= @paciente.grau_instrucao %>
</p>

<p>
  <b>E-mail:</b>
  <%= @paciente.email %>
</p>

<p>
  <b>Telefone:</b>
  <%= @paciente.telefone %>
</p>

<p>
  <b>Endereço:</b>
  <%= @paciente.endereco %>
</p>

<p>
  <b>Complemento:</b>
  <%= @paciente.complemento %>
</p>

<p>
  <b>Bairro:</b>
  <%= @paciente.bairro %>
</p>

<p>
  <b>Cidade:</b>
  <%= @paciente.cidade %>
</p>

<p>
  <b>Estado:</b>
  <%= @paciente.estado %>
</p>

<p>
  <b>CEP:</b>
  <%= @paciente.cep %>
</p>

<p>
  <b>Profissão:</b>
  <%= @paciente.profissao %>
</p>

<p>
  <b>Observação:</b>
  <%= @paciente.observacao %>
</p>

</div>