config/routes.rb
ProjetoFinal::Application.routes.draw do

  resources :exames, except: [:edit, :update, :destroy] do
    member do
		  get :concluir
		  put :salvar_conclusao
	  end
	  
	  collection do
      get :concluidas
      get :consultar_concluidas
      get :consultar_marcadas
    end
	  
  end
  
  resources :marcacoes, except: [:edit, :update, :destroy] do
		member do
		  get :concluir
		  put :salvar_conclusao
	  end

	  collection do
      get :concluidas
      get :consultar_concluidas
      get :consultar_marcadas
    end
	end

  resources :especialidades

  devise_for :funcionarios, controllers: { registrations: 'funcionarios' }

  resources :funcionarios do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :pacientes do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :postos do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :medicos do
    collection do
      get :informacoes
      get :consultar
    end
  end

root to: "home#index"
 
end

app/models/exame.rb
class Exame < ActiveRecord::Base
  belongs_to :paciente
  belongs_to :medico

      validates :paciente, :medico, :data, :hora, :tipo, presence: true
      
     def concluido?
    		data_conclusao.present?
  	end

end

app/controllers/exames_controller.rb
class ExamesController < ApplicationController
    load_and_authorize_resource 
      before_filter :authenticate_funcionario!
      
		def new
			@exame = Exame.new
		end

		def create
    @exame = Exame.new(params[:exame])

    if @exame.save
      flash[:notice] = "Exame realizado com sucesso"
      redirect_to @exame
    else
      render action:"new"
    end
  end

  def show
    @exame = Exame.find(params[:id])
  end

  def index
    @exames = Exame.all
  end
  
  def concluir
    		@exame = Exame.find(params[:id])
  end

  def salvar_conclusao
    @exame = Exame.find(params[:id])

    respond_to do |format|
      if @exame.update_attributes(params[:exame])
        format.html { redirect_to @exame, notice: 'Exame concluido com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "concluir" }
        format.json { render json: @exame.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def concluidas
    @exames = Exame.all
  end

  def consultar_concluidas
    data = params[:data].to_date
    puts data
    @exames = Exame.where('data = ?', data)
    render 'concluidas'
  end
  
  def consultar_marcadas
    data = params[:data].to_date
    puts data
    @exames = Exame.where('data = ?', data)
    render 'index'
  end
  
end

app/views/exames/_form.html.erb
<div id="formulario">

  <%= semantic_form_for(@exame) do |f| %>

      <fieldset class="dados_fieldset">
        <legend> Dados Paciente</legend>
          <br>
          <%= f.input :paciente, member_label: :nome, include_blank: true%>
      </fieldset>

<br><br>

      <fieldset class="dados_fieldset">
        <legend> Dados Médico</legend>
          <br>
          <%= f.input :medico, member_label: :nome, include_blank: true %>
      </fieldset>

<br><br>

      <fieldset class="dados_fieldset">
        <legend> Dados Exame</legend>
          <br>
          <%= f.input :data, as: :string, label: "Data Exame", input_html: opcoes_para_data %>

          <%= f.input :hora %>

          <%= f.input :tipo, as: :select, collection: ["Agendamento", "Emergencial"]%>

      </fieldset>

        <br><br>

      <%= f.submit 'Salvar' %>
<% end %>

</div>

app/views/exames/concluidas.html.erb
<div id="medico">

<h1>Exames Concluídos</h1>

<div id='consulta'>
   <%= form_tag consultar_concluidas_exames_path, method: :get do %>
     <%= label_tag :data, 'Busca por data' %>
     <%= text_field_tag :data %>
     <%= submit_tag 'Buscar' %>
   <% end %>
</div>

<table id="relatorio">
  <tr>
    <th>Paciente</th>
    <th>Médico</th>
    <th>Data</th>
    <th>Hora</th>
    <th>Data Conclusão</th>
    <th>Conclusão</th>
  </tr>

  <% for exame in @exames %>

    <% if exame.concluido? %>
        <tr>
          <td><p><%= exame.paciente.nome %></p></td>
          <td><p><%= exame.medico.nome %></p></td>
          <td><p><%= exame.data.to_s_br %></p></td>
          <td><p><%= exame.hora %></p></td>
          <td><p><%= exame.data_conclusao.to_s_br%></p></td>
          <td><p><%= exame.conclusao %><p></td>

        </tr>
    <% else %>

    <% end %>
  <%end%>
</table>

</div>

app/views/exames/concluir.html.erb
<h1>Concluir Exame</h1>
<br>
<%= semantic_form_for @exame, url: salvar_conclusao_exame_path(@exame), method: :put do |f| %>

   <%= f.input :conclusao, label: "Conclusão",  as: :select, collection: ["Compareceu", "Não Compareceu", "Desmarcou"]%>
   <%= f.input :data_conclusao, as: :string, label: "Data",
       input_html: { value: Date.today.to_s_br } %>
   <%= f.submit 'Concluir Exame'%>
<% end %>

app/views/exames/index.html.erb
<div id="medico">

<h1>Baixar Exame</h1>

<div id='consulta'>
   <%= form_tag consultar_marcadas_exames_path, method: :get do %>
     <%= label_tag :data, 'Busca por data' %>
     <%= text_field_tag :data %>
     <%= submit_tag 'Buscar' %>
   <% end %>
</div>

<table id="relatorio">
  <tr>
    <th>Paciente</th>
    <th>Médico</th>
    <th>Data</th>
    <th>Hora</th>
    <th>Data Conclusão</th>
    <th> </th>
  </tr>

  <% for exame in @exames %>

  <% if exame.concluido? %>

  <% else %>
    <tr>
      <td><p><%= exame.paciente.nome %></p></td>
      <td><p><%= exame.medico.nome %></p></td>
      <td><p><%= exame.data.to_s_br %></p></td>
      <td><p><%= exame.hora %></p></td>
      <td><p><%= exame.data_conclusao.to_s_br%></p></td>
      <td>
        <%= link_to 'Concluir', concluir_exame_path(exame) %>
        <%end%>
    </tr>

  <% end %>
</table>

</div>

app/views/exames/new.html.erb
<div id="paciente">

<h1>Marcar Exame</h1>

<%= render 'form' %>

</div>

app/views/exames/show.html.erb
<div id="medico">

<p>
  <b>Paciente:</b>
  <%= @exame.paciente.nome %>
</p>

<p>
  <b>Médico:</b>
  <%= @exame.medico.nome %>
</p>

<p>
  <b>Data Exame:</b>
  <%= @exame.data.to_s_br %>
</p>

<p>
  <b>Hora:</b>
  <%= @exame.hora %>
</p>

<p>
  <b>Tipo:</b>
  <%= @exame.tipo %>
</p>

</div>