config/routes.rb
ProjetoFinal::Application.routes.draw do

  resources :exames, except: [:edit, :update, :destroy] do
    member do
		  get :concluir
		  put :salvar_conclusao
	  end
	  
	  collection do
      get :concluidas
      get :consultar_concluidas
      get :consultar_marcadas
    end
	  
  end
  
  resources :marcacoes, except: [:edit, :update, :destroy] do
		member do
		  get :concluir
		  put :salvar_conclusao
	  end

	  collection do
      get :concluidas
      get :consultar_concluidas
      get :consultar_marcadas
    end
	end

  resources :especialidades

  devise_for :funcionarios, controllers: { registrations: 'funcionarios' }

  resources :funcionarios do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :pacientes do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :postos do
    collection do
      get :informacoes
      get :consultar
    end
  end

  resources :medicos do
    collection do
      get :informacoes
      get :consultar
    end
  end

root to: "home#index"
 
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base

belongs_to :posto

 devise :database_authenticatable, :registerable, :lockable, :timeoutable,
        :recoverable, :trackable

    validates :nome, :cpf, :rg, :sexo, :data_nascimento, :estado_civil, :cor, :naturalidade,
  :grau_instrucao, :email, :telefone, :endereco, :bairro, :cidade, :estado, :cep,
   :password, :password_confirmation, :posto, presence: true

  validates :email, format:/^.+\@.+\..+$/

  usar_como_cpf :cpf

  validates :email, :cpf, uniqueness:true
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController

  load_and_authorize_resource 
  before_filter :authenticate_funcionario!
  
  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @funcionarios }
    end
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
    @funcionario = Funcionario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @funcionario }
    end
  end

  # GET /funcionarios/new
  # GET /funcionarios/new.json
  def new
    @funcionario = Funcionario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @funcionario }
    end
  end

  # GET /funcionarios/1/edit
  def edit
    @funcionario = Funcionario.find(params[:id])
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(params[:funcionario])

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario cadastrado com sucesso.' }
        format.json { render json: @funcionario, status: :created, location: @funcionario }
      else
        format.html { render action: "new" }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /funcionarios/1
  # PUT /funcionarios/1.json
  def update
    @funcionario = Funcionario.find(params[:id])

    respond_to do |format|
      if @funcionario.update_attributes(params[:funcionario])
        format.html { redirect_to @funcionario, notice: 'Funcionario alterado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario = Funcionario.find(params[:id])
    @funcionario.destroy

    respond_to do |format|
      format.html { redirect_to funcionarios_url }
      format.json { head :no_content }
    end
  end

  def informacoes
  end

  def consultar
    nome = params[:nome]
    @funcionarios = Funcionario.where('UPPER(nome) LIKE ?', "%#{nome.upcase}%")
    render 'index'
  end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<div id="formulario">

<%= semantic_form_for(@funcionario) do |f| %>


  <fieldset class="dados_fieldset">
    <legend> Dados Pessoais</legend>
    <br>
        <%= f.input :nome %>

        <%= f.input :cpf, label: "CPF", input_html: opcoes_para_cpf %>

        <%= f.input :rg, label: "RG"%>

        <%= f.input :sexo, as: :select, collection: ["Masculino", "Feminino"]%>

        <%= f.input :data_nascimento, as: :string, label: "Data Nascimento",
          input_html: opcoes_para_data %>

        <%= f.input :estado_civil, as: :select, collection: ["Solteiro", "Casado", "Separado", "Viúvo"] %>

        <%= f.input :cor, as: :select, collection: ["Negro", "Mulato Escuro", "Mulato Médio",
      "Mulato Claro", "Branco"] %>

        <%= f.input :naturalidade %>

        <%= f.input :grau_instrucao, label: "Grau Instrução"%>
  </fieldset>

  <br><br>

  <fieldset class="dados_fieldset">
    <legend> Dados Contato</legend>
    <br>

        <%= f.input :email, label: "E-mail"%>

        <%= f.input :telefone, input_html: opcoes_para_telefone %>

        <%= f.input :endereco, label: "Endereço"%>

        <%= f.input :complemento %>

        <%= f.input :bairro %>

        <%= f.input :cidade %>

        <%= f.input :estado, as: :select, collection: ["Acre", "Alagoas", "Amazonas", "Amapá", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rondônia", "Rio Grande do Sul", "Roraima", "Santa Catarina", "Sergipe", "São Paulo", "Tocantins"] %>

        <%= f.input :cep, label: "CEP", input_html: opcoes_para_cep %>
  </fieldset>

  <br><br>

  <fieldset class="dados_fieldset">
    <legend> Dados Autenticação</legend>
    <br>
        <%= f.input :password, label: 'Senha' %>
        <%= f.input :password_confirmation, as: :password, label: 'Confirmação' %>
  </fieldset>

  <br><br>

  <fieldset class="dados_fieldset">
    <legend> Dados Posto</legend>
      <br>

   		<%= f.input :posto, member_label: :nome, include_blank: true%>
      <%= f.input :tipo, as: :select, collection: ["Administrador", "Atendente"] %>      
   	</fieldset>




<br><br>
  <%= f.submit 'Salvar' %>
<% end %>

</div>

app/views/funcionarios/edit.html.erb
<h1>Alterar Funcionário</h1>

<%= render 'form' %>

app/views/funcionarios/index.html.erb
<div id="funcionario">

<h1>Consultar Funcionário</h1>

<div id='consulta'>
   <%= form_tag consultar_funcionarios_path, method: :get do %>
     <%= label_tag :nome, 'Busca por nome' %>
     <%= text_field_tag :nome %>
     <%= submit_tag 'Buscar' %>
   <% end %>
</div>

<table id="relatorio">
  <tr>
    <th>Nome</th>
    <th>Rg</th>
    <th>Email</th>
    <th>Telefone</th>
    <th>Endereco</th>
    <th>Posto</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @funcionarios.each do |funcionario| %>
  <tr>
    <td><%= funcionario.nome %></td>
    <td><%= funcionario.rg %></td>
    <td><%= funcionario.email %></td>
    <td><%= funcionario.telefone %></td>
    <td><%= funcionario.endereco %></td>
    <td><%= funcionario.posto.nome %></td>
    <td><%= link_to 'Ver', funcionario %></td>
    <td><%= link_to 'Alterar', edit_funcionario_path(funcionario) %></td>
    <td><%= link_to 'Apagar', funcionario, confirm: 'Realmente deseja apagar?', method: :delete %></td>
  </tr>
<% end %>
</table>
</br>

</div>

app/views/funcionarios/informacoes.html.erb
<div id="funcionario">
  <h1>Funcionário</h1>

</div>

app/views/funcionarios/new.html.erb
<div id= "funcionario">
<h1>Cadastrar Funcionário</h1>

<%= render 'form' %>

</div>

app/views/funcionarios/show.html.erb
<div id="funcionario">

<p>
  <b>Nome:</b>
  <%= @funcionario.nome %>
</p>

<p>
  <b>CPF:</b>
  <%= @funcionario.cpf %>
</p>

<p>
  <b>RG:</b>
  <%= @funcionario.rg %>
</p>

<p>
  <b>Sexo:</b>
  <%= @funcionario.sexo %>
</p>

<p>
  <b>Data Nascimento:</b>
  <%= @funcionario.data_nascimento.to_s_br %>
</p>

<p>
  <b>Estado civil:</b>
  <%= @funcionario.estado_civil %>
</p>

<p>
  <b>Cor:</b>
  <%= @funcionario.cor %>
</p>

<p>
  <b>Naturalidade:</b>
  <%= @funcionario.naturalidade %>
</p>

<p>
  <b>Grau Instrução:</b>
  <%= @funcionario.grau_instrucao %>
</p>

<p>
  <b>E-mail:</b>
  <%= @funcionario.email %>
</p>

<p>
  <b>Telefone:</b>
  <%= @funcionario.telefone %>
</p>

<p>
  <b>Endereço:</b>
  <%= @funcionario.endereco %>
</p>

<p>
  <b>Complemento:</b>
  <%= @funcionario.complemento %>
</p>

<p>
  <b>Bairro:</b>
  <%= @funcionario.bairro %>
</p>

<p>
  <b>Cidade:</b>
  <%= @funcionario.cidade %>
</p>

<p>
  <b>Estado:</b>
  <%= @funcionario.estado %>
</p>

<p>
  <b>CEP:</b>
  <%= @funcionario.cep %>
</p>

<p>
  <b>Posto:</b>
  <%= @funcionario.posto.nome %>
</p>

<p>
  <b>Tipo:</b>
  <%= @funcionario.tipo %>
</p>


</div>